#:schema node_modules/wrangler/config-schema.json
name = "calibrator-calibrate"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "calibrator-calibrate.alvgaona.dev", custom_domain = true },
]

secrets_store_secrets = [
  { binding = "R2_ACCESS_KEY_ID", store_id = "faf3b8ff9bed4854b1839f3d0067210b", secret_name = "R2_ACCESS_KEY_ID" },
  { binding = "R2_SECRET_ACCESS_KEY", store_id = "faf3b8ff9bed4854b1839f3d0067210b", secret_name = "R2_SECRET_ACCESS_KEY" },
]

[vars]
AWS_REGION = "us-east-1"

[[queues.consumers]]
queue = "calibrate-queue"
max_batch_size = 10
max_batch_timeout = 60

[[containers]]
max_instances = 10
name = "calibrate"
class_name = "Calibrate"
image = "registry.cloudflare.com/590d5e6a4382a813b506fa45ca1609e0/calibrate:latest"

[[durable_objects.bindings]]
name = "Calibrate"
class_name = "Calibrate"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Calibrate"]
