// Generated by Wrangler on Mon Sep 02 2024 14:38:42 GMT-0300 (Argentina Standard Time)
// by running `wrangler types`

interface Env {
  ACCOUNT_ID: string;
  ACCESS_KEY_ID: string;
  SECRET_ACCESS_KEY: string;
}
