// Generated by Wrangler on Wed Sep 11 2024 21:28:18 GMT-0300 (Argentina Standard Time)
// by running `wrangler types`

interface Env {
  ACCOUNT_ID: '590d5e6a4382a813b506fa45ca1609e0';
  UPLOAD_BUCKET: 'calibrator-upload';
}
