// Generated by Wrangler on Sun Sep 08 2024 22:26:35 GMT-0300 (Argentina Standard Time)
// by running `wrangler types`

interface Env {
  CALIBRATOR_INPUT_BUCKET: R2Bucket;
  CALIBRATOR_OUTPUT_BUCKET: R2Bucket;
}
