#:schema node_modules/wrangler/config-schema.json
name = "calibrator-upload"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "calibrator-upload.alvgaona.dev", custom_domain = true }]

[vars]
ACCOUNT_ID = "590d5e6a4382a813b506fa45ca1609e0"
UPLOAD_BUCKET = "calibrator-upload"
