name = "hello-world"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-10"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[queues.consumers]]
queue = "calibrator-unpack"
dead_letter_queue = "calibrator-unpack-dlq"

[[r2_buckets]]
binding = "CALIBRATOR_INPUT_BUCKET"
bucket_name = "calibrator-input"

[[r2_buckets]]
binding = "CALIBRATOR_UPLOAD_BUCKET"
bucket_name = "calibrator-upload"
